### ISSUE TITLE
opportunity to use / learn pathlib

### ISSUE THREAD

**Issue by skewty** [caol64/ps2mc-browser#4]
https://github.com/caol64/ps2mc-browser/blob/81c724ed731c17979068d1b7253d5516e2a3f85c/src/browser.py#L28

Great job.. I was surprised to see so many non Java and python native language constructs used. You clearly did a lot of python learning before taking on the project.  Good on you.

That said, it is my opinion that pathlib.Path should be used here instead. I am guess it is a module you haven't gotten to yet.

label / tag as [improvement]

**Comment by caol64** [comment]
@skewty Thank you for your advice. There is still a lot for me to learn in Python, and I will follow your suggestion to delve into the pathlib module and other 'pythonic' aspects. Thanks again.
